services:
  rekor:
    image: ghcr.io/sigstore/rekor/rekor-server:v1.3.6
    container_name: rbi-rekor
    command: serve --enable_retrieve_api=false --trillian_log_server.address="" --trillian_log_server.port=0
    ports: ["9000:3000"]
    restart: "no"
  awardos-gateway:
    build:./gateway
    container_name: awardos-gateway
    ports: ["8443:8443"]
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    depends_on:
    restart: "no"
  llm:
    image: ollama/ollama:0.1.26
    container_name: balk-llm
    command: serve
